title: <p align="center"> Gaetano Chiriaco</p>

logo: "/images/profilepic.jpeg?raw=true"

description:
  <p align="center">
  Milan, Italy | g.chiriaco@hotmail.it
  <br> <a href="pdf/CV_ENG.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gaetano-chiriaco-68085820b/">LinkedIn</a> |
  <a href="https://github.com/gaetanochiriaco">GitHub</a> 
  <br> 24 y/o | M. Sc. in Data Science | B. Sc. in Statistics </p>
  

  
theme: jekyll-theme-minimal


